export const alpacaConfig = [
  {
    id: 0,
    label: "Backgrounds",
    directory: "backgrounds",
    selected: false,
    items: [
      {
        id: 0,
        label: "Default",
        filename: "default",
        selected: false,
        src: "/alpaca/backgrounds/default.png",
      },
      {
        id: 1,
        label: "Blue 50",
        filename: "blue50",
        selected: false,
        src: "/alpaca/backgrounds/blue50.png",
      },
      {
        id: 2,
        label: "Blue 60",
        filename: "blue60",
        selected: false,
        src: "/alpaca/backgrounds/blue60.png",
      },
      {
        id: 3,
        label: "Blue 70",
        filename: "blue70",
        selected: false,
        src: "/alpaca/backgrounds/blue70.png",
      },
      {
        id: 4,
        label: "Green 60",
        filename: "green60",
        selected: false,
        src: "/alpaca/backgrounds/green60.png",
      },
      {
        id: 5,
        label: "Green 70",
        filename: "green70",
        selected: false,
        src: "/alpaca/backgrounds/green70.png",
      },
      {
        id: 6,
        label: "Grey 40",
        filename: "grey40",
        selected: false,
        src: "/alpaca/backgrounds/grey40.png",
      },
      {
        id: 7,
        label: "Grey 70",
        filename: "grey70",
        selected: false,
        src: "/alpaca/backgrounds/grey70.png",
      },
      {
        id: 8,
        label: "Grey 80",
        filename: "grey80",
        selected: false,
        src: "/alpaca/backgrounds/grey80.png",
      },
      {
        id: 9,
        label: "Red 50",
        filename: "red50",
        selected: false,
        src: "/alpaca/backgrounds/red50.png",
      },
      {
        id: 10,
        label: "Red 60",
        filename: "red60",
        selected: false,
        src: "/alpaca/backgrounds/red60.png",
      },
      {
        id: 11,
        label: "Red 70",
        filename: "red70",
        selected: false,
        src: "/alpaca/backgrounds/red70.png",
      },
      {
        id: 12,
        label: "Yellow 50",
        filename: "yellow50",
        selected: false,
        src: "/alpaca/backgrounds/yellow50.png",
      },
      {
        id: 13,
        label: "Yellow 60",
        filename: "yellow60",
        selected: false,
        src: "/alpaca/backgrounds/yellow60.png",
      },
      {
        id: 14,
        label: "Yellow 70",
        filename: "yellow70",
        selected: false,
        src: "/alpaca/backgrounds/yellow70.png",
      },
    ],
  },
  {
    id: 1,
    label: "Ears",
    directory: "ears",
    selected: false,
    items: [
      {
        id: 0,
        label: "Default",
        filename: "default",
        selected: false,
        src: "/alpaca/ears/default.png",
      },
      {
        id: 1,
        label: "Tilt Backward",
        filename: "tilt-backward",
        selected: false,
        src: "/alpaca/ears/tilt-backward.png",
      },
      {
        id: 2,
        label: "Tilt Forward",
        filename: "tilt-forward",
        selected: false,
        src: "/alpaca/ears/tilt-forward.png",
      },
    ],
  },
  {
    id: 2,
    label: "Eyes",
    directory: "eyes",
    selected: false,
    items: [
      {
        id: 0,
        label: "Default",
        filename: "default",
        selected: false,
        src: "/alpaca/eyes/default.png",
      },
      {
        id: 1,
        label: "Angry",
        filename: "angry",
        selected: false,
        src: "/alpaca/eyes/angry.png",
      },
      {
        id: 2,
        label: "Naughty",
        filename: "naughty",
        selected: false,
        src: "/alpaca/eyes/naughty.png",
      },
      {
        id: 3,
        label: "Panda",
        filename: "panda",
        selected: false,
        src: "/alpaca/eyes/panda.png",
      },
      {
        id: 4,
        label: "Smart",
        filename: "smart",
        selected: false,
        src: "/alpaca/eyes/smart.png",
      },
      {
        id: 5,
        label: "Star",
        filename: "star",
        selected: false,
        src: "/alpaca/eyes/star.png",
      },
    ],
  },
  {
    id: 3,
    label: "Hair",
    directory: "hair",
    selected: false,
    items: [
      {
        id: 0,
        label: "Default",
        filename: "default",
        selected: false,
        src: "/alpaca/hair/default.png",
      },
      {
        id: 1,
        label: "Bang",
        filename: "bang",
        selected: false,
        src: "/alpaca/hair/bang.png",
      },
      {
        id: 2,
        label: "Curls",
        filename: "curls",
        selected: false,
        src: "/alpaca/hair/curls.png",
      },
      {
        id: 3,
        label: "Elegant",
        filename: "elegant",
        selected: false,
        src: "/alpaca/hair/elegant.png",
      },
      {
        id: 4,
        label: "Fancy",
        filename: "fancy",
        selected: false,
        src: "/alpaca/hair/fancy.png",
      },
      {
        id: 5,
        label: "Short",
        filename: "short",
        selected: false,
        src: "/alpaca/hair/short.png",
      },
    ],
  },
  {
    id: 4,
    label: "Leg",
    directory: "leg",
    selected: false,
    items: [
      {
        id: 0,
        label: "Default",
        filename: "default",
        selected: false,
        src: "/alpaca/leg/default.png",
      },
      {
        id: 1,
        label: "Bubble Tea",
        filename: "bubble-tea",
        selected: false,
        src: "/alpaca/leg/bubble-tea.png",
      },
      {
        id: 2,
        label: "Cookie",
        filename: "cookie",
        selected: false,
        src: "/alpaca/leg/cookie.png",
      },
      {
        id: 3,
        label: "Game Console",
        filename: "game-console",
        selected: false,
        src: "/alpaca/leg/game-console.png",
      },
      {
        id: 4,
        label: "Tile Backward",
        filename: "tilt-backward",
        selected: false,
        src: "/alpaca/leg/tilt-backward.png",
      },
      {
        id: 5,
        label: "Tilt Forward",
        filename: "tilt-forward",
        selected: false,
        src: "/alpaca/leg/tilt-forward.png",
      },
    ],
  },
  {
    id: 5,
    label: "Mouth",
    directory: "mouth",
    selected: false,
    items: [
      {
        id: 0,
        label: "Default",
        filename: "default",
        selected: false,
        src: "/alpaca/mouth/default.png",
      },
      {
        id: 1,
        label: "Astonished",
        filename: "astonished",
        selected: false,
        src: "/alpaca/mouth/astonished.png",
      },
      {
        id: 2,
        label: "Eating",
        filename: "eating",
        selected: false,
        src: "/alpaca/mouth/eating.png",
      },
      {
        id: 3,
        label: "Laugh",
        filename: "laugh",
        selected: false,
        src: "/alpaca/mouth/laugh.png",
      },
      {
        id: 4,
        label: "Tongue",
        filename: "tongue",
        selected: false,
        src: "/alpaca/mouth/tongue.png",
      },
    ],
  },
  {
    id: 6,
    label: "Neck",
    directory: "neck",
    selected: false,
    items: [
      {
        id: 0,
        label: "Default",
        filename: "default",
        selected: false,
        src: "/alpaca/neck/default.png",
      },
      {
        id: 1,
        label: "Bend Backward",
        filename: "bend-backward",
        selected: false,
        src: "/alpaca/neck/bend-backward.png",
      },
      {
        id: 2,
        label: "Bend Forward",
        filename: "bend-forward",
        selected: false,
        src: "/alpaca/neck/bend-forward.png",
      },
      {
        id: 3,
        label: "Thick",
        filename: "thick",
        selected: false,
        src: "/alpaca/neck/thick.png",
      },
    ],
  },
  {
    id: 7,
    label: "Accessories",
    directory: "accessories",
    selected: false,
    items: [
      {
        id: 0,
        label: "Default",
        filename: "default",
        selected: false,
        src: "/alpaca/accessories/default.png",
      },
      {
        id: 1,
        label: "Earings",
        filename: "earings",
        selected: false,
        src: "/alpaca/accessories/earings.png",
      },
      {
        id: 2,
        label: "Flower",
        filename: "flower",
        selected: false,
        src: "/alpaca/accessories/flower.png",
      },
      {
        id: 3,
        label: "Glasses",
        filename: "glasses",
        selected: false,
        src: "/alpaca/accessories/glasses.png",
      },
    ],
  },
  {
    id: 8,
    label: "Nose",
    directory: "nose",
    selected: false,
    items: [
      {
        id: 0,
        label: "Default",
        filename: "default",
        selected: false,
        src: "/alpaca/nose/default.png",
      },
    ],
  },
];
